-- convert data for personbean
SELECT 'INSERT INTO personbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, beruf, beruffamilysearch,  konfession,  konfessionfamilysearch,  location,  locationfamilysearch,  mann,  mutterfamilysearch,  mutterid,  nachname,  nachnamefamilysearch,  notice,  vaterfamilysearch,  vaterid,  vornamen,  vornamenfamilysearch) VALUES (' || id || ', ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', ''' || beruf || ''', ' || beruffamilysearch || ', ''' || konfession || ''', ' || konfessionfamilysearch || ', ''' || wohnort || ''', ' || wohnortfamilysearch || ', ' || (geschlecht = 'm') || ', ' || mutterfamilysearch || ', ' || mutterid || ', ''' || nachname || ''', ' || nachnamefamilysearch || ', ''' || notiz || ''', ' || vaterfamilysearch || ', ' || vaterid || ', ''' || vornamen || ''', ' || vornamenfamilysearch || ');' FROM person;

-- convert data for eventbean
SELECT 'INSERT INTO eventbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, eventtype, familysearch, hochzeitid, jahr, location, monat, nachweis, notice, personid, source, tag, typ) VALUES ((SELECT nextval(''hibernate_sequence'')), ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', ''BIRTH'', ' || geburtsdatumfamilysearch || ', null, ' || geburtsjahr || ', ''' || geburtsort || ''', ' || geburtsmonat || ', ''' || geburtsdokumentexistent || ''', ''' || geburtsnotiz || ''', ' || id || ', ''' || geburtsquelle || ''', ' || geburtstag || ', ''' || geburtsdatumtyp || ''');' FROM person;

SELECT 'INSERT INTO eventbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, eventtype, familysearch, hochzeitid, jahr, location, monat, nachweis, notice, personid, source, tag, typ) VALUES ((SELECT nextval(''hibernate_sequence'')), ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', ''BAPTISM'', ' || taufdatumfamilysearch || ', null, ' || taufjahr || ', ''' || taufort || ''', ' || taufmonat || ', ''' || taufdokumentexistent || ''', ''' || taufnotiz || ''', ' || id || ', ''' || taufquelle || ''', ' || tauftag || ', ''' || taufdatumtyp || ''');' FROM person;

SELECT 'INSERT INTO eventbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, eventtype, familysearch, hochzeitid, jahr, location, monat, nachweis, notice, personid, source, tag, typ) VALUES ((SELECT nextval(''hibernate_sequence'')), ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', ''DEATH'', ' || sterbedatumfamilysearch || ', null, ' || sterbejahr || ', ''' || sterbeort || ''', ' || sterbemonat || ', ''' || sterbedokumentexistent || ''', ''' || sterbenotiz || ''', ' || id || ', ''' || sterbequelle || ''', ' || sterbetag || ', ''' || sterbedatumtyp || ''');' FROM person;

SELECT 'INSERT INTO eventbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, eventtype, familysearch, hochzeitid, jahr, location, monat, nachweis, notice, personid, source, tag, typ) VALUES ((SELECT nextval(''hibernate_sequence'')), ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', ''MARRIAGE'', ' || familysearch || ', ' || id || ', ' || jahr || ', ''' || ort || ''', ' || monat || ', ''' || dokumentexistent || ''', ''' || notiz || ''', null, ''' || quelle || ''', ' || tag || ', ''' || datumtyp || ''');' FROM heirat;

-- create queries for hochzeitbean
SELECT 'INSERT INTO hochzeitbean (id, changed_date, changed_uid, created_date, created_uid, deleted, uuid, divorce, frauid, mannid, marriage) VALUES (' || id || ', ''' || changeddate || ''', 1, null, 1, ' || deleted || ', ''' || uuid_generate_v1() || ''', false, ' || frauid || ', ' || mannid || ', true);' FROM heirat;

UPDATE eventbean SET typ = 'EXACT' WHERE typ = 'DAY' OR typ = 'NONE' OR typ IS NULL;